export { default as UserIcon } from './user-icon';
export { default as CartIcon } from './cart-icon';
export { default as HamburgerIcon } from './hamburger-icon';
export { default as VisaIcon } from './visa-icon';
export { default as MasterCardIcon } from './mastercard-icon';
export { default as PaypalIcon } from './paypal-icon';
export { default as VisaElectronIcon } from './visa-electron-icon';
export { default as ArrowRightIcon } from './arrow-right-icon';
export { default as SearchIcon } from './search-icon';
